services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:latest
    container_name: flask-web
    restart: unless-stopped
    ports:
      - "5111:5000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=5000
      - DEBUG=true
      - ENVIRONMENT=development
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: flask-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
